### ISSUE TITLE
no mesh in exported FMDL file

### ISSUE THREAD

**Issue by NevilleZms** [BobDoleOwndU/FMDL-Studio-v2#17]
Hi,
I exported model from Unity to fmdl file without any error message, but when I re import the fmdl, there is no mesh present, only skeletons. What am I missing here? I followed the tutorial closely and I used Maya for importing and exporting the fbx file. The mesh path is: 00.dat/Assets/tpp/pack/player/parts/plparts_ddf_swimwear_h

**Comment by NevilleZms** [comment]
It turns out that I misplaced the shader.

**Comment by ProxyFenix** [comment]
Sorry, I have the same problem. Could you explain how did you fix it?

**Comment by NevilleZms** [comment]
Basically you want to make sure every mesh element has the correct material assigned to it.
