### ISSUE TITLE
Models shadows disappear in certain areas with shadows set to extra high.

### ISSUE THREAD

**Issue by NevilleZms** [BobDoleOwndU/FMDL-Studio-v2#18]
Hi,
I used the FMDL studio to import a customized character into the game, and I am encountering an issue with the character's shadow. Under extra high shadow setting, the character shadow doesn't show up in certain areas. For example, the character shadow would disappear when I am near the airport in Africa. Also, the shadow casting distance for the character is significantly reduced as well, causing the shadow to dither or disappear when the character is on the high ground. Everything else with the imported model is working correctly, including models, animation, textures and shaders.

Low to High shadow setting eliminate the shadow disappearing issue in the airport, but the shadow casting distance is still reduced.

Any help would be appreciated.

**Comment by BobDoleOwndU** [comment]
Somebody else has mentioned this bug before. I'm not entirely sure what causes it. I think it's related to the bounding boxes somehow since the Fox Engine seems to use those to calculate shadows. I'm still not 100% sure how the relationship between bounding boxes and shadows works though.

**Comment by NevilleZms** [comment]
You are right. The issue is gone after I manually copy and paste another model's bounding box. In my case, I copied the heavy armor's bounding box to my model. Thank you for the help

**Comment by BobDoleOwndU** [comment]
I believe this should be fixed in the [1.6 Beta pre-release](https://github.com/BobDoleOwndU/FMDL-Studio-v2/releases/tag/1.6b). Just waiting for some people to test and confirm.
