### ISSUE TITLE
Elevate log message about missing texture to warning or error

### ISSUE THREAD

**Issue by youarebritish** [BobDoleOwndU/FMDL-Studio-v2#19]
It would be useful if errors encountered during import (such as missing shaders or textures) were a warning or error, to bring the user's attention to the problem. Consider using [AssetImportContext.LogImportError()](https://docs.unity3d.com/ScriptReference/Experimental.AssetImporters.AssetImportContext.LogImportError.html) or [AssetImportContext.LogImportWarning()](https://docs.unity3d.com/ScriptReference/Experimental.AssetImporters.AssetImportContext.LogImportWarning.html).

**Comment by BobDoleOwndU** [comment]
Added in the 1.6.1 Beta pre-release.
