### ISSUE TITLE
Using Fmdl Studio 2 with PES 2019 or PES 2020 models

### ISSUE THREAD

**Issue by dissectionalone** [BobDoleOwndU/FMDL-Studio-v2#21]
Has anyone had success Exporting PES 2019/2020 models? I was attempting to change a hair model (by adding a mesh object from another hair model) but naming convention requirements of the Element 0 appears to cause issues with export results... Not sure what the differences are (hierarchy wise) between the Metal Gear models and the PES ones . Is there a tested method for exporting an edited fmdl from PES 2019? 

Cheers

**Comment by BobDoleOwndU** [comment]
Are you adding the extra mesh directly in Unity? If so, that can cause issues with bone weights. Meshes usually need to be added and weighted in a 3D modelling program before using Fmdl Studio to export the edited model to an fmdl.

**Comment by dissectionalone** [comment]
I am but I've actually imported both fmdl hair files, then made a duplicate
of the mesh object I wanted to add and copied/moved it to the target hair
model, in an attempt to avoid losing stuff from the fmdl file. I haven't
tested combining the mesh objects, then exporting to FBX and reimporting
though. Would that approach be best suited for this?

BobDoleOwndU <notifications@github.com> escreveu no dia domingo, 8/12/2019
à(s) 01:19:

**Comment by BobDoleOwndU** [comment]
The best approach would be to export both models to FBX, combine them in 3DS Max (or another equivalent modelling program), then import the custom FBX and built the fmdl from that.

**Comment by dissectionalone** [comment]
I've done a bit of testing (actually like what you suggested but curiously
prior to your reply) but on those tests I couldn't find the best way ot
have the hierarchy
 set up... The Parent object on PES 2019 models is named *root *(I'm
assuming this is the "dummy" pivot bone) and in the specific case of hair
models, which is what I'm noodling around with, the lowest mesh object (and
first child of the *root* bone) is supposed to be named *MESH_HAIR_0 *but
FMDL Studio expects *element 0 *to be named *MESH_ROOT*, right?

I guess these two differences might be tampering the results.

Should I add another child object (before *MESH_HAIR_0 *on this example)
and name it *MESH_ROOT *and import it like that into Unity?

Thanks for the replies :) I really appreciate the feedback

BobDoleOwndU <notifications@github.com> escreveu no dia quarta, 11/12/2019
à(s) 00:24:

**Comment by BobDoleOwndU** [comment]
Ah. So this relates to the FoxModel component directly if I understand correctly.

If I understand, Fmdl Studio won't let you export because the first mesh group isn't named MESH_ROOT, right?

This may be a difference in MGSV and PES models. All models in MGSV do contain a MESH_ROOT mesh group as their first mesh group; but this might not be the case for PES models.

**Comment by BobDoleOwndU** [comment]
But yes. Adding a MESH_ROOT mesh group as the first mesh group should allow you to export.

**Comment by dissectionalone** [comment]
Yeah the PES models don't have a MESH_ROOT as element 0. I admit haven't
payed attention to other models from the game (even ones I've actually
imported before like players limbs) but I'll check what's element 0 on
those, but I'm wondering to what extent is the naming convention expected
by FMDL Studio kinda hindering the process...

Once again, many thanks for the feedback :)

BobDoleOwndU <notifications@github.com> escreveu no dia quarta, 11/12/2019
à(s) 23:26:

**Comment by BobDoleOwndU** [comment]
I'll remove the naming requirement for it in a future update.

**Comment by dissectionalone** [comment]
Thank you very much, mate. Appreciate it :)

BobDoleOwndU <notifications@github.com> escreveu no dia sexta, 13/12/2019
à(s) 02:43:

**Comment by Donniebalubun** [comment]
hello sir

**Comment by BobDoleOwndU** [comment]
Fixed in the [1.8.1 Beta](https://github.com/BobDoleOwndU/FMDL-Studio-v2/releases/tag/1.8.1b) release.
