### ISSUE TITLE
FMDL Presetup (Question)

### ISSUE THREAD

**Issue by Murkur** [BobDoleOwndU/FMDL-Studio-v2#27]
What am I expected to use to get the files down to a FMDL format and DDS texture format? using GzsTool just converts them to their native FOXEngine models.

**Comment by BobDoleOwndU** [comment]
You use Fmdl Studio v2 to import the .fmdl files. To convert the textures, from .ftex to .ftexs, use [FtexTool](https://github.com/Atvaark/FtexTool).

**Comment by Murkur** [comment]
> You use Fmdl Studio v2 to import the .fmdl files. To convert the textures from .ftex to .dds, use [FtexTool](https://github.com/Atvaark/FtexTool).

how would I extract FMDL files? GZSTool doesnt seem to be exporting any fmdl files for me

**Comment by BobDoleOwndU** [comment]
You use GzsTool to open the game's .dat files. Inside the extracted .dat files will be .fpk files (among a lot of other files). Some of the .fpk files will contain the .fmdl files.

**Comment by Murkur** [comment]
ahh didnt know you had to run it through multiple times thanks ❤️
