### ISSUE TITLE
Question - How to export to Blender with Textures linked/intact?

### ISSUE THREAD

**Issue by ROBYER1** [BobDoleOwndU/FMDL-Studio-v2#31]
Is there a way to export using the .dae or .fbx exporter with textures linked? Currently when I export, the files are exported with materials that have no texture connections (even just the texture slots there but not attached I could fix). Is there a way to export with textures linked or embedded or even just have the texture slots there with the texture name but the file doesn't have to be linked so it can be fixed in Blender?
![tex](https://user-images.githubusercontent.com/10745594/145440682-0cdd5143-1d50-4038-8f48-bbaf26fdac89.png)

Just asking as it is very lengthy to go one by one through each exported model, add the texture slots to any materials and connect the textures when I could just use 'Find Missing Files' or scripting in Blender to connect the textures - something like this would be great even if the file was missing
![ideal](https://user-images.githubusercontent.com/10745594/145440658-668b3a6d-e0dc-4a0e-b34f-1feadc665320.png)

**Comment by BobDoleOwndU** [comment]
The COLLADA files should be exported with the albedo texture connected. The issue with the others is that the Fox Engine has its own unique shader system that would require custom shaders in Blender.

Also Blender currently doesn't import COLLADA models' normals, so the Autodesk FBX Converter is required to get the models to import with the normals intact. I believe the converter also strips the textures from the model; so even if all of the textures were connected, they'd end up getting stripped by the converter.

So unfortunately, as of now, I don't have a good solution for this.

**Comment by ROBYER1** [comment]
I guess as I'm looking to port some assets to other engines and formats, I may be best off looking into making an editor script that converts the materials you have generated into URP Default Lit materials. This would be so that I could use an exporter like GLTFast (Unity GLTF) or the Autodesk FBX exporter. As the meshes are only stored in the scene as far as I can see this may introduce other issues with exporting.

I'll report back with my findings as I would like to find a tidy way to export these assets to GLTF for use in other environments than just Fox Engine mods 🙏

**Comment by ROBYER1** [comment]
Closing this as I have opened a new issue which is probably just the blocker for what I'm trying to do in terms of automation with exporting including textures. Once that bug is fixed I can write a Blender script which searches for and hooks up the other textures if they are available!
