### ISSUE TITLE
Exported FBX with Collada export with multiple materials has jumbled texture names

### ISSUE THREAD

**Issue by ROBYER1** [BobDoleOwndU/FMDL-Studio-v2#32]
When exporting a Collada and importing the FBX that is exported alongside it into Blender, meshes that have multiple materials on children all have the same incorrect texture assigned to their materials in the albedo slot. It seems the exported is choosing one of the textures on one of the materials and setting that as the texture for all of them.

I have set up a quick repro package for you to try this out with screenshots/steps below:

Package: https://drive.google.com/file/d/13rOcfMcPeqjPVLBGXvhfmTgEKXDQQP93/view?usp=sharing

Raw FMDL file: https://drive.google.com/file/d/10muxsXlmtPZwZR-27P766AFvXOUZMuu-/view?usp=sharing

Exported FBX file: https://drive.google.com/file/d/1_rdOA0LF19dQ_VNmLOCB7dpSUaMuN-D9/view?usp=sharing

1. Open up a project with FMDL Studio v2 in, import this package:
2.Set texture folder to Textures/PTUnconverted (you may have to reimport the package after)

3. Open up scenes > Hallway1 - If we select just the wall Geo and inspect the texture slots on the mortar material:
![image](https://user-images.githubusercontent.com/10745594/145710451-861ccc2b-823b-49b6-9170-7fb8a80f2994.png)

4. We have this tex:
![image](https://user-images.githubusercontent.com/10745594/145710457-ca9d0b37-c1a2-49e9-a71a-44af86b4b4a2.png)

5. On export, select the top of the hierarchy - 'shsb_hous001' and use FMDL Studio > Convert To Collada
6. Open Blender, import the FBX that is exported alongside the Collada

7. Check the materials on the model, they all have the same texture name 'shsb_hous001_d8_bsm_alp' which is also missing the '.dds'
![image](https://user-images.githubusercontent.com/10745594/145710628-28a86ebc-3b04-4362-8bf1-4d5244e68cf9.png)
![image](https://user-images.githubusercontent.com/10745594/145710654-db11df8a-c21c-4858-8fcf-16743a24c10d.png)

I was originally planning to auto find all the textures for the materials in blender and fix up the texture slots that were missing via script. I did a lot of this work and when it did work I noticed that it was pulling the same texture onto all of the materials. After digging deeper I found this issue with the exporter. If this can be fixed I will share my scripts for automating texture assignments in Blender to help others!

**Comment by BobDoleOwndU** [comment]
Other than the .dds part of the filename missing (which seems to have been stripped by the FBX converter), I am not able to replicate this issue. The materials all have the correct texture listed on my end, using both the fmdl you provided as well as others I've checked.

**Comment by ROBYER1** [comment]
Thanks for looking into this, I'll probably just close this for now as I went through and relinked all the textures manually in Blender anyway. If anyone has the same issue they can always reopen this, must be something to do with Unity editor itself or Blender version!

Have a great Christmas
